// Chapter 14 — Introduction to Classes · Project: The Fraction Class  (GRADER)
// ─────────────────────────────────────────────────────────────────────────────
// Tiny no-framework unit-test harness (matches the CLAUDE.md spec). Picks up
// the learner's header via -Istarter (make test) or the reference via -Isolution
// (make test-solution) — that path-switch IS the Style B2 trick (CLAUDE.md §B2).
//
// CHECKs are grouped by task. Each group tests the HAPPY PATH (typical inputs)
// and at least one EDGE CASE (zero, negative, same-class access, etc.).
//
// Do NOT edit this file — it is the grader contract.

#include <iostream>
#include <string>
#include "fraction.h"    // resolved to starter/ or solution/ via -I on the command line

static int fails = 0;

// CHECK: if cond is false, print the failing expression + line number.
#define CHECK(cond) \
    do { if (!(cond)) { \
        std::cerr << "FAIL: " #cond "  @line " << __LINE__ << "\n"; \
        ++fails; \
    } } while (0)

int main()
{
    // ── Task 1: Default constructor ───────────────────────────────────────────
    // Fraction{} must produce 0/1 (the "additive zero" identity).
    {
        Fraction z {};
        CHECK(z.numerator()   == 0);
        CHECK(z.denominator() == 1);
        CHECK(z.isValid());
        CHECK(z.toString() == "0/1");
    }

    // ── Task 2: Two-argument constructor — normal cases ───────────────────────
    {
        Fraction half { 1, 2 };
        CHECK(half.numerator()   == 1);
        CHECK(half.denominator() == 2);
        CHECK(half.isValid());
    }
    {
        Fraction neg { -3, 4 };
        CHECK(neg.numerator()   == -3);
        CHECK(neg.denominator() == 4);    // denominator stays positive
    }

    // ── Task 2: Two-argument constructor — sign normalization ─────────────────
    // Fraction{1,-2} must store as -1/2 (denominator always positive).
    {
        Fraction negDenom { 1, -2 };
        CHECK(negDenom.numerator()   == -1);
        CHECK(negDenom.denominator() == 2);
    }
    // Fraction{-3,-4} = 3/4 (both signs cancel, result is positive).
    {
        Fraction negBoth { -3, -4 };
        CHECK(negBoth.numerator()   == 3);
        CHECK(negBoth.denominator() == 4);
    }

    // ── Task 2: Two-argument constructor — reduction ──────────────────────────
    // 4/6 reduces to 2/3; 6/4 reduces to 3/2; 0/7 reduces to 0/1.
    {
        Fraction r1 { 4, 6 };
        CHECK(r1.numerator()   == 2);
        CHECK(r1.denominator() == 3);
    }
    {
        Fraction r2 { 6, 4 };
        CHECK(r2.numerator()   == 3);
        CHECK(r2.denominator() == 2);
    }
    {
        // Edge: 0/7 — numerator is 0; fraction is 0/1 after reduction.
        Fraction zero { 0, 7 };
        CHECK(zero.numerator()   == 0);
        CHECK(zero.denominator() == 1);
    }
    {
        // Edge: numerator equals denominator -> 1/1.
        Fraction one { 5, 5 };
        CHECK(one.numerator()   == 1);
        CHECK(one.denominator() == 1);
    }
    {
        // Edge: bad denominator 0 -> fall back to n/1 (per spec).
        Fraction bad { 3, 0 };
        CHECK(bad.isValid());
        CHECK(bad.denominator() != 0);
    }
    {
        // Edge: negative numerator with denominator that shares a factor.
        // -6/-4 => sign cancel => 6/4 => reduces to 3/2.
        Fraction r3 { -6, -4 };
        CHECK(r3.numerator()   == 3);
        CHECK(r3.denominator() == 2);
    }

    // ── Task 3: Explicit whole-number constructor ─────────────────────────────
    // Fraction{5} must build 5/1.  The `explicit` keyword prevents implicit
    // conversion: the tests below must use explicit construction syntax.
    {
        Fraction five { Fraction(5) };
        CHECK(five.numerator()   == 5);
        CHECK(five.denominator() == 1);
    }
    {
        Fraction neg { Fraction(-3) };
        CHECK(neg.numerator()   == -3);
        CHECK(neg.denominator() == 1);
    }
    {
        // Edge: whole-number zero.
        Fraction z { Fraction(0) };
        CHECK(z.numerator()   == 0);
        CHECK(z.denominator() == 1);
    }

    // ── Task 4: const member functions on const objects ───────────────────────
    // A const Fraction must be callable for read-only accessors.
    {
        const Fraction cf { 2, 3 };
        CHECK(cf.numerator()   == 2);
        CHECK(cf.denominator() == 3);
        CHECK(cf.isValid());
    }
    {
        // Through a const reference (the common call site in real code).
        const Fraction& cref { Fraction(7, 8) };
        CHECK(cref.numerator()   == 7);
        CHECK(cref.denominator() == 8);
    }

    // ── Task 5: equals() ──────────────────────────────────────────────────────
    {
        Fraction a { 1, 2 };
        Fraction b { 1, 2 };
        CHECK(a.equals(b));           // same fraction
        CHECK(b.equals(a));           // symmetric

        Fraction c { 2, 3 };
        CHECK(!a.equals(c));          // different fractions

        // Two representations of the same value must both reduce to 2/3.
        Fraction d { 4, 6 };
        Fraction e { 2, 3 };
        CHECK(d.equals(e));           // edge: 4/6 == 2/3 after reduction

        // Whole-number vs fraction form.
        Fraction whole { Fraction(1) };
        Fraction frac  { 3, 3 };
        CHECK(whole.equals(frac));    // 1/1 == 3/3-reduced = 1/1

        // Zero equality.
        Fraction z1 { 0, 5 };
        Fraction z2 {};
        CHECK(z1.equals(z2));         // edge: 0/5 reduces to 0/1 == 0/1

        // Negative fractions.
        Fraction neg1 { -1, 2 };
        Fraction neg2 { 1, -2 };      // stores as -1/2
        CHECK(neg1.equals(neg2));     // both should reduce to -1/2
    }

    // ── Task 6: multipliedBy() ────────────────────────────────────────────────
    {
        // (1/2) * (2/3) = 2/6 = 1/3.
        Fraction half   { 1, 2 };
        Fraction third  { 2, 3 };
        Fraction result { half.multipliedBy(third) };
        CHECK(result.numerator()   == 1);
        CHECK(result.denominator() == 3);
        CHECK(result.equals(Fraction { 1, 3 }));
    }
    {
        // (3/4) * (4/3) = 12/12 = 1/1.
        Fraction a { 3, 4 };
        Fraction b { 4, 3 };
        CHECK(a.multipliedBy(b).equals(Fraction(1)));  // whole-number result
    }
    {
        // Edge: multiply by 0 -> 0/1.
        Fraction a { 1, 2 };
        Fraction zero {};
        Fraction r { a.multipliedBy(zero) };
        CHECK(r.numerator()   == 0);
        CHECK(r.denominator() == 1);
    }
    {
        // Edge: multiply two negatives -> positive.
        // (-1/2) * (-2/3) = 2/6 = 1/3.
        Fraction a { -1, 2 };
        Fraction b { -2, 3 };
        Fraction r { a.multipliedBy(b) };
        CHECK(r.numerator()   == 1);
        CHECK(r.denominator() == 3);
    }
    {
        // Edge: multiply whole number * fraction.
        Fraction two  { Fraction(2) };     // 2/1
        Fraction half { 1, 2 };            // 1/2
        CHECK(two.multipliedBy(half).equals(Fraction(1)));  // 2/2 = 1/1
    }
    {
        // Original object must be UNCHANGED (multipliedBy is const, returns new).
        Fraction orig { 3, 4 };
        Fraction other { 2, 5 };
        Fraction r { orig.multipliedBy(other) };
        CHECK(orig.numerator()   == 3);  // orig untouched
        CHECK(orig.denominator() == 4);
        CHECK(r.numerator()   == 3);     // 6/20 reduces to 3/10
        CHECK(r.denominator() == 10);
    }

    // ── toString / print helpers (provided scaffolding, just sanity-check) ────
    {
        Fraction f { 3, 5 };
        CHECK(f.toString() == "3/5");

        Fraction neg { -1, 4 };
        CHECK(neg.toString() == "-1/4");
    }

    // ── Summary ───────────────────────────────────────────────────────────────
    if (!fails)
        std::cout << "PASS \xE2\x9C\x85 all Fraction checks passed.\n";
    else
        std::cerr << "\nFAIL \xE2\x9D\x8C " << fails
                  << " check(s) failed — fix the TASK blocks in fraction.h.\n";

    return fails ? 1 : 0;
}
