// ============================================================================
//  tests/tests.cpp  —  the automated grader for the generic toolkit (Ch 11)
// ----------------------------------------------------------------------------
//  A no-framework unit-test harness (same style as drills/CLAUDE.md).
//  Includes ../toolkit.h and calls every function across many inputs.
//
//  This is Style B2 (header-only): there are no .cpp implementation files.
//  The Makefile swaps implementations purely by include path — `-Istarter`
//  (make test) vs `-Isolution` (make test-solution) — so this same file
//  #includes EITHER starter/toolkit.h OR solution/toolkit.h. The template
//  definitions in toolkit.h are always visible to this file, so template
//  instantiation happens here at compile time (notes 11.10).
//
//  DO NOT EDIT THIS FILE — it is the contract.
//
//  Coverage map:
//    describe(int)         — TASK 1: exact int overload (notes 11.2)
//    describe(double)      — TASK 2: exact double overload (notes 11.2)
//    describe(bool)        — TASK 3: bool overload prevents int-promotion (11.3)
//    describe(string_view) — TASK 4: string_view overload (notes 11.2)
//    myMin<T>              — TASK 5: single-type template + explicit arg (11.6, 11.7)
//    myClamp<T>            — TASK 6: template with boundary logic (11.6, 11.7)
//    repeatChar<N>         — TASK 7: non-type template parameter (notes 11.9)
//    scaled<T,U>           — TASK 8: two-type template + auto return (notes 11.8)
//    formatCount           — TASK 9: default arguments (notes 11.5)
// ============================================================================

#include <iostream>
#include <cmath>        // std::abs for floating-point comparison
#include "toolkit.h"   // found via -Istarter or -Isolution (Style B2)

// Convenience: std::string_view literal suffix (C++17)
using namespace std::string_view_literals;

static int fails = 0;

// CHECK: exact boolean condition; on failure print expression + line number.
#define CHECK(cond) \
    do { if(!(cond)){ std::cerr << "FAIL: " #cond "  @line " << __LINE__ << "\n"; ++fails; } } while(0)

// CHECK_NEAR: floating-point equality within a small epsilon.
#define CHECK_NEAR(got, want) \
    do { auto g_=(got); auto w_=(want); \
         if(std::abs(static_cast<double>(g_) - static_cast<double>(w_)) > 1e-9){ \
             std::cerr << "FAIL: " #got " ~= " #want \
                       << "  (got " << g_ << ", want " << w_ << ")  @line " << __LINE__ << "\n"; \
             ++fails; } } while(0)

int main()
{
    // ── Task 1: describe(int) — exact int overload ───────────────────────────
    // These must call describe(int), NOT describe(double) or describe(bool).
    // If the int overload is missing or wrong, the label will not start "int:".
    CHECK(describe(0)    == "int:0");
    CHECK(describe(1)    == "int:1");
    CHECK(describe(-1)   == "int:-1");
    CHECK(describe(42)   == "int:42");
    CHECK(describe(-99)  == "int:-99");
    CHECK(describe(100)  == "int:100");

    // ── Task 2: describe(double) — exact double overload ─────────────────────
    // An integer literal like `0` would pick describe(int); the `0.0` suffix
    // forces a double literal and the double overload (notes 11.2 / 11.3).
    CHECK(describe(0.0)   == "double:0.0");
    CHECK(describe(1.0)   == "double:1.0");
    CHECK(describe(-1.0)  == "double:-1.0");
    CHECK(describe(3.14)  == "double:3.14");
    CHECK(describe(2.5)   == "double:2.5");
    CHECK(describe(-0.5)  == "double:-0.5");
    CHECK(describe(99.9)  == "double:99.9");

    // ── Task 3: describe(bool) — bool overload beats int promotion ───────────
    // KEY RESOLUTION CHECK: bool promotes to int (notes 11.3), so without the
    // bool overload describe(true) would return "int:1". The exact bool overload
    // must fire instead. This makes the promotion rule VISIBLE.
    CHECK(describe(true)  == "bool:true");
    CHECK(describe(false) == "bool:false");
    // Verify the bool overload does NOT delegate to the int path:
    CHECK(describe(true)  != "int:1");    // must be "bool:true", not int path
    CHECK(describe(false) != "int:0");    // must be "bool:false", not int path

    // ── Task 4: describe(std::string_view) — string overload ─────────────────
    // We pass string_view values (using the sv literal suffix) rather than raw
    // string literals. Why? A plain "hello" has type const char*, which converts
    // to bool (a standard conversion, step 3) before converting to string_view
    // (a user-defined conversion, step 4) — so without the sv suffix the bool
    // overload would win, hiding the string overload entirely (notes 11.3).
    // The sv suffix makes the argument ALREADY a string_view — exact match, step 1.
    CHECK(describe("hello"sv) == "str:hello");
    CHECK(describe("LLVM"sv)  == "str:LLVM");
    CHECK(describe(""sv)      == "str:");    // edge: empty string_view

    // ── Task 5: myMin<T> — single-type template + explicit template arg ───────
    // Deduction cases: compiler infers T from the argument types.
    CHECK(myMin(3, 5)      == 3);          // T=int deduced; 3 < 5 -> 3
    CHECK(myMin(5, 3)      == 3);          // T=int; 3 < 5 -> 3
    CHECK(myMin(0, 0)      == 0);          // edge: equal values
    CHECK(myMin(-1, 1)     == -1);         // T=int, negative
    CHECK(myMin(-5, -3)    == -5);         // edge: both negative; -5 < -3
    CHECK_NEAR(myMin(1.5, 2.5), 1.5);     // T=double, deduced
    CHECK_NEAR(myMin(3.0, 3.0), 3.0);     // edge: equal doubles

    // Explicit template argument (notes 11.7): myMin<double>(int, double)
    // forces T=double so the int 3 is converted to 3.0 before comparison.
    CHECK_NEAR(myMin<double>(3, 4.5), 3.0);   // explicit T=double, int->double
    CHECK_NEAR(myMin<double>(10, 2.7), 2.7);  // explicit T=double

    // ── Task 6: myClamp<T> — template with boundary clamping ─────────────────
    // Value already in range:
    CHECK(myClamp(5, 1, 10)   == 5);   // T=int, in range, pass-through
    CHECK(myClamp(1, 1, 10)   == 1);   // edge: exactly lo, pass-through
    CHECK(myClamp(10, 1, 10)  == 10);  // edge: exactly hi, pass-through
    // Value below lo:
    CHECK(myClamp(0, 1, 10)   == 1);   // below lo -> clamp to lo
    CHECK(myClamp(-5, 0, 3)   == 0);   // negative value clamped to 0
    // Value above hi:
    CHECK(myClamp(15, 1, 10)  == 10);  // above hi -> clamp to hi
    CHECK(myClamp(100, 0, 3)  == 3);   // far above hi
    // Double version:
    CHECK_NEAR(myClamp(0.5, 1.0, 5.0), 1.0);   // below lo -> 1.0
    CHECK_NEAR(myClamp(3.0, 1.0, 5.0), 3.0);   // in range
    CHECK_NEAR(myClamp(7.5, 1.0, 5.0), 5.0);   // above hi -> 5.0
    // Edge: lo == hi -> always clamped to that single value
    CHECK(myClamp(0, 3, 3)    == 3);
    CHECK(myClamp(5, 3, 3)    == 3);

    // ── Task 7: repeatChar<N> — non-type template parameter ──────────────────
    // Each distinct N is a SEPARATE instantiation with its OWN static buf (11.9).
    CHECK(repeatChar<1>('x')  == "x");
    CHECK(repeatChar<3>('*')  == "***");
    CHECK(repeatChar<5>('-')  == "-----");
    CHECK(repeatChar<4>('a')  == "aaaa");
    CHECK(repeatChar<2>(' ')  == "  ");    // edge: spaces
    // Size must match N exactly:
    CHECK(repeatChar<3>('x').size() == 3);
    CHECK(repeatChar<5>('!').size() == 5);
    // Different N values -> truly different instantiations: sizes differ.
    CHECK(repeatChar<1>('z').size() != repeatChar<3>('z').size());

    // ── Task 8: scaled<T,U> — two-type template, auto return ─────────────────
    // int * int -> int
    CHECK(scaled(4, 3)        == 12);    // T=int, U=int -> int
    CHECK(scaled(0, 99)       == 0);     // edge: zero factor
    CHECK(scaled(-2, 5)       == -10);   // negative
    // int * double -> double (auto return captures the wider type)
    CHECK_NEAR(scaled(3, 2.5),  7.5);   // T=int, U=double -> double 7.5
    CHECK_NEAR(scaled(2, 1.5),  3.0);
    // double * double -> double
    CHECK_NEAR(scaled(1.5, 2.0), 3.0);  // T=double, U=double
    CHECK_NEAR(scaled(0.5, 4.0), 2.0);

    // ── Task 9: formatCount — default argument ────────────────────────────────
    // Singular (count == 1): no suffix appended.
    CHECK(formatCount("item",  1)         == "1 item");
    CHECK(formatCount("error", 1)         == "1 error");
    CHECK(formatCount("test",  1)         == "1 test");
    // Plural with default suffix "s":
    CHECK(formatCount("item",  3)         == "3 items");   // "item" + "s"
    CHECK(formatCount("error", 5)         == "5 errors");  // "error" + "s"
    CHECK(formatCount("bug",   2)         == "2 bugs");    // "bug" + "s"
    CHECK(formatCount("item",  0)         == "0 items");   // edge: 0 is plural
    // Explicit suffix override:
    CHECK(formatCount("pass",  2, "es")   == "2 passes");  // "pass" + "es"
    CHECK(formatCount("match", 3, "es")   == "3 matches"); // "match" + "es"
    CHECK(formatCount("fox",   2, "es")   == "2 foxes");   // "fox" + "es"
    // Singular with explicit suffix — suffix still ignored for count==1:
    CHECK(formatCount("pass",  1, "es")   == "1 pass");
    CHECK(formatCount("item",  1, "xyz")  == "1 item");

    if (!fails)
        std::cout << "PASS \xe2\x9c\x85  all toolkit checks passed.\n";
    else
        std::cerr << "\nFAIL \xe2\x9d\x8c  " << fails << " check(s) failed — fix the TASK blocks.\n";

    return fails ? 1 : 0;
}
