// Chapter 8 — Control Flow · Project: The Number-Guessing Engine
// ─────────────────────────────────────────────────────────────────────────────
// This header is the CONTRACT between you and the grader. It declares the six
// PURE functions that make up the guessing-game engine. DO NOT EDIT THIS FILE —
// tests/tests.cpp includes it, and so do BOTH starter/engine.cpp (yours) and
// solution/engine.cpp (the reference). Change a signature and nothing links.
//
// THE BIG IDEA OF THIS LAB: separate the *logic* from the *randomness and I/O*.
//   • The engine below is PURE: every function looks only at its arguments and
//     returns a value — no std::cin, no std::cout, NO <random>. That makes it
//     fully DETERMINISTIC, so the grader can pin down exact answers.
//   • The dice-rolling, the seeding, the "type a guess" prompt — all of that
//     lives in main() (see starter/main.cpp), which WRAPS this engine. The notes
//     call this out: keep the Mersenne-Twister RNG and the I/O OUT of the logic
//     you want to test. (CS6340: the same split lets you unit-test a fuzzer's
//     decision logic without actually launching the random target.)
//
// Each function exercises a different Chapter-8 control-flow tool: an if/else
// chain, a switch, a while loop, a do-while validation loop, and a for loop with
// break/continue. Your whole job is to wire up that control flow correctly.
//
// Header guard (Chapter 2): stops this file being pasted in twice per build.
#ifndef ENGINE_H
#define ENGINE_H

#include <string>        // std::string       — owned, mutable text (Chapter 5)
#include <string_view>   // std::string_view  — cheap, non-owning view (Chapter 5)

// ─── TASK 1 ──────────────────────────────────────────────────────────────────
// judgeGuess — the heart of the game. Compare a guess against the secret and
// report the DIRECTION as a three-way result code (think of a comparator, or
// strcmp): the SIGN of the answer tells the player which way to move.
//
//     guess  <  secret   ->  return -1   ("your guess is too LOW,  go higher")
//     guess  >  secret   ->  return +1   ("your guess is too HIGH, go lower")
//     guess  == secret   ->  return  0   ("CORRECT")
//
// Implement it with an if / else if / else CHAIN (the cases are mutually
// exclusive — exactly one branch should run). No loops here.
int judgeGuess(int secret, int guess);

// ─── TASK 2 ──────────────────────────────────────────────────────────────────
// hintText — turn a three-way code from judgeGuess into a human label, using a
// SWITCH statement (this is the switch task — please don't use if/else here):
//     -1 -> "too low"
//      0 -> "correct"
//     +1 -> "too high"
// Any other value -> "invalid" via the `default` case. Remember `break` after
// each case so you don't fall through into the next one.
std::string_view hintText(int code);

// ─── TASK 3 ──────────────────────────────────────────────────────────────────
// sumOfDigits — add up the decimal digits of `n` with a LOOP (`while` or `for`),
// peeling one digit at a time with `% 10` (the last digit) and `/ 10` (drop it).
// The digit sum is defined on the MAGNITUDE, so a negative n uses its absolute
// value: sumOfDigits(-123) == 6, same as sumOfDigits(123). sumOfDigits(0) == 0.
// (Assume n > INT_MIN — that one value's magnitude doesn't fit in an int.)
// (This is the chapter's "loop-driven numeric tool" — pure counting, no I/O.)
int sumOfDigits(int n);

// ─── TASK 4 ──────────────────────────────────────────────────────────────────
// countdownString — build the launch countdown as a STRING using a `while` loop,
// counting DOWN from `start` to 1, then appending the finale:
//     countdownString(3) == "3..2..1..liftoff"
//     countdownString(1) == "1..liftoff"
//     countdownString(0) == "liftoff"   // loop body runs zero times
// Note there is NO ".." before "liftoff" and NONE after the final number — the
// separator ".." goes only BETWEEN counts. (Returning a string, not printing,
// is what makes this testable — main() can std::cout it later.)
std::string countdownString(int start);

// ─── TASK 5 ──────────────────────────────────────────────────────────────────
// promptsUntilValid — a DETERMINISTIC stand-in for a do-while input loop. The
// notes' do-while example keeps re-prompting until the user types an in-range
// value; here the "typed" values are handed to you up front as a string of
// single digits (e.g. "0093" means the user typed 0, then 0, then 9, then 3),
// so the grader can test it without std::cin.
//
// Walk the digits left-to-right with a `do { … } while (…)` loop. Count how many
// you consume until you hit one that is IN RANGE [low, high]; return that 1-based
// COUNT (the digit's value, not its index). A do-while is the right shape here:
// you always read at least ONE value before you can judge it.
//   promptsUntilValid("7",    1, 6) == 1   // first read (7) is out of range… but
//                                           //   it is the ONLY one, so 1 prompt
//   promptsUntilValid("093",  1, 6) == 3   // 0 bad, 9 bad, 3 good -> 3rd prompt
//   promptsUntilValid("4",    1, 6) == 1   // valid on the very first prompt
// If NONE are valid, you'll have consumed them all: return that total count.
// Assume `typed` is non-empty and contains only the characters '0'..'9'.
int promptsUntilValid(std::string_view typed, int low, int high);

// ─── TASK 6 ──────────────────────────────────────────────────────────────────
// playRound — the capstone, and the chapter's own number-guessing capstone in
// pure form. Play one bounded round against `secret`. The player's guesses are
// the digit characters of `guesses` (each char '0'..'9' is one numeric guess).
// You get at most `maxAttempts` *counted* attempts.
//
// Loop over the guesses with a `for` loop. For each character:
//   • Convert it to its int value (e.g. '7' -> 7).
//   • If that value is OUTSIDE [0, 9]… it can't happen here (digits only), but
//     the real rule you must implement is: a guess equal to the SENTINEL 0 means
//     "skip / misclick" — do NOT count it and `continue` to the next character.
//   • Otherwise it's a real attempt: judge it with judgeGuess. If it's correct,
//     `break` out and return the 1-based number of the COUNTED attempt that won.
//   • Stop once you've used `maxAttempts` counted attempts (a loss).
// Return the winning attempt number (1-based), or 0 if the player never guessed
// `secret` within the budget. This pulls together for + if + break + continue.
//   playRound(5, "375", 3) == 3   // guesses 3,7,5 -> 3rd attempt wins
//   playRound(5, "12",  3) == 0   // never guessed 5 -> loss
//   playRound(5, "059", 3) == 0   // the 0 is skipped (not counted); 5,9 miss
//   playRound(5, "5",   3) == 1   // first counted attempt wins
int playRound(int secret, std::string_view guesses, int maxAttempts);

#endif // ENGINE_H
