// ============================================================================
//  starter/main.cpp  —  DEMO DRIVER for the report-logger family  (Ch 24)
// ----------------------------------------------------------------------------
//  This is an UNGRADED demo that exercises your logger implementation.
//  Run it with: make run
//
//  DO NOT EDIT THIS FILE — it is provided scaffolding.
//  Your work is in starter/logger.cpp (the TASK blocks).
//
//  When your TASK blocks are complete, this demo will print the construction
//  order, the formatted log entries, and the static-binding cliffhanger.
// ============================================================================

#include <iostream>
#include <string>
#include "logger.h"

int main()
{
    std::cout << "============================================================\n";
    std::cout << "  Chapter 24 — Inheritance: Report-Logger Family Demo\n";
    std::cout << "============================================================\n\n";

    // ── 1. Basic Logger ───────────────────────────────────────────────────────
    std::cout << "── 1. Basic Logger ─────────────────────────────────────────\n";
    {
        std::string ct, dt;
        Logger base { "system", ct, dt };

        std::cout << "  name(): " << base.name() << "\n";
        std::cout << "  log(\"boot\"):    " << base.log("boot") << "\n";
        std::cout << "  log(\"running\"): " << base.log("running") << "\n";
    }
    std::cout << "\n";

    // ── 2. Construction order proof (notes 24.3) ──────────────────────────────
    std::cout << "── 2. Construction / destruction order (notes 24.3) ────────\n";
    {
        std::string ct, dt;
        {
            TimestampLogger tl { "audit", "[T]", ct, dt };
            std::cout << "  ctor trace: \"" << ct << "\"\n";
        }
        std::cout << "  dtor trace: \"" << dt << "\"\n";
    }
    std::cout << "\n";

    // ── 3. TimestampLogger::log() (notes 24.7) ────────────────────────────────
    std::cout << "── 3. TimestampLogger::log() (notes 24.7) ───────────────────\n";
    {
        std::string ct, dt;
        TimestampLogger tl { "router", "[T]", ct, dt };
        std::cout << "  tl.log(\"connect\") = \"" << tl.log("connect") << "\"\n";
    }
    std::cout << "\n";

    // ── 4. CountingLogger (notes 24.5, 24.6) ─────────────────────────────────
    std::cout << "── 4. CountingLogger (notes 24.5 / 24.6) ───────────────────\n";
    {
        std::string ct, dt;
        CountingLogger cl { "counter", ct, dt };
        cl.log("startup");
        cl.log("shutdown");
        std::cout << "  linesLogged() = " << cl.linesLogged() << "\n";
    }
    std::cout << "\n";

    // ── 5. THE CLIFFHANGER — static binding (notes 24.7) ──────────────────────
    std::cout << "── 5. THE CLIFFHANGER: static binding (notes 24.7) ─────────\n";
    {
        std::string ct, dt;
        TimestampLogger tl { "router", "[T]", ct, dt };

        std::cout << "  Direct:            \"" << tl.log("direct") << "\"\n";
        std::cout << "  Via Logger& ref:   \"" << processLog(tl, "via_ref") << "\"\n";
        std::cout << "  (no tag in second call — Logger::log() ran, not TimestampLogger::log())\n";
    }

    std::cout << "\n============================================================\n";
    std::cout << "  Run `make test` to grade your implementation.\n";
    std::cout << "============================================================\n";

    return 0;
}
