// Chapter 15 — More on Classes · Project: IdCard Badge Printer
// ─────────────────────────────────────────────────────────────────────────────
// This header is the CONTRACT between the learner, the grader, and the solution.
// DO NOT EDIT THIS FILE.  tests/tests.cpp includes it; both starter/idcard.cpp
// and solution/idcard.cpp include it. Change a signature and nothing links.
//
// THE BIG PICTURE OF THIS LAB
// ────────────────────────────
// A real software system often splits a class into TWO files:
//
//   idcard.h      — the CLASS DEFINITION: member declarations, access specifiers,
//                   nested types, static member *declarations*. ONE canonical copy.
//   idcard.cpp    — the OUT-OF-CLASS DEFINITIONS of every non-trivial member body.
//
// That split (notes 15.2) is what you implement. The header you are reading right
// now is fully complete and compiles. Your job is to write the matching bodies in
// starter/idcard.cpp using the ClassName::method() syntax (notes 15.2).
//
// Along the way you will make five Chapter-15 concepts physical:
//
//   (a) `this`           – the explicit `this->m_member = param;` idiom (15.1).
//   (b) Method chaining  – setOwner/setTitle return IdCard& so calls can chain.
//   (c) Static members   – s_liveCount tracks live IdCard objects class-wide;
//                          s_nextSerial auto-assigns unique serial numbers.
//   (d) Destructor       – decrements s_liveCount; tests use nested { } scopes so
//                          you can OBSERVE the count fall deterministically.
//   (e) Nested type      – Role enum class lives inside IdCard (notes 15.3).
//
// CS6340 tie-in: LLVM's class hierarchy (llvm::Value, llvm::Instruction, …) uses
// exactly this layout — declarations in .h, definitions in .cpp, static helpers
// for global counts/tables, and explicit `this->` in template methods. Reading
// this header and then writing the .cpp mirrors how you'll navigate LLVM source.
//
// Header guard (notes 15.2 / Chapter 2): prevents double-inclusion in one TU.
#ifndef IDCARD_H
#define IDCARD_H

#include <string>        // std::string        (Chapter 5)
#include <string_view>   // std::string_view   (Chapter 5)

// ═════════════════════════════════════════════════════════════════════════════
// class IdCard
// ═════════════════════════════════════════════════════════════════════════════
// An employee ID card that tracks a name, a title, a role category, and a
// unique serial number. The class also counts how many IdCard objects are
// currently alive (s_liveCount) and auto-issues serial numbers (s_nextSerial).
//
// Key class-mechanics at a glance (see the notes' "Class mechanics map"):
//
//     IdCard(std::string_view owner, std::string_view title);  // ctor
//     ~IdCard();                          // dtor — Chapter 15.4
//
//     IdCard& setOwner(std::string_view owner);   // returns *this — Chapter 15.1
//     IdCard& setTitle(std::string_view title);   // returns *this — Chapter 15.1
//
//     std::string_view owner()  const;    // const accessor
//     std::string_view title()  const;    // const accessor
//     Role             role()   const;    // const accessor
//     int              serial() const;    // const accessor
//
//     IdCard& setRole(Role r);            // role setter — returns *this
//
//     static int  liveCount();            // class-level counter — Chapter 15.7
//     static int  nextSerial();           // peek at the next serial to be issued
// ─────────────────────────────────────────────────────────────────────────────
class IdCard
{
public:
    // ── Nested type (notes 15.3) ──────────────────────────────────────────────
    // Role lives *inside* IdCard because it is meaningless outside the badge
    // system. Callers use IdCard::Role::Engineer, not a bare Role. (LLVM uses
    // the same pattern for e.g. llvm::Instruction::OtherOps.)
    enum class Role
    {
        Engineer,
        Manager,
        Intern,
        Other,
    };

    // ── Constructor ───────────────────────────────────────────────────────────
    // Initialises the card, increments s_liveCount, and claims the next serial.
    // Default arguments (notes 15.2): declared once HERE in the header only —
    // do NOT repeat them in the .cpp definition.
    explicit IdCard(std::string_view owner = "Unnamed",
                    std::string_view title = "Untitled");

    // ── Destructor (notes 15.4) ───────────────────────────────────────────────
    // Called automatically when the object's lifetime ends (scope exit, etc.).
    // Decrements s_liveCount so you can OBSERVE the count fall in tests.
    ~IdCard();

    // ── Setters — each returns *this by reference (notes 15.1) ───────────────
    // Returning IdCard& (reference, NOT a copy!) enables chaining:
    //     card.setOwner("Ada").setTitle("Eng").setRole(IdCard::Role::Engineer);
    // Task: write the explicit-`this` idiom `this->m_member = param;` (notes 15.1).
    // Here the `m_` prefix means `m_owner` and the parameter `owner` are different
    // names, so `this->` is a clarity convention; it is strictly REQUIRED only when
    // a parameter and a member share the same name.
    IdCard& setOwner(std::string_view owner);
    IdCard& setTitle(std::string_view title);
    IdCard& setRole(Role role);

    // ── Const accessors ───────────────────────────────────────────────────────
    std::string_view owner()  const;
    std::string_view title()  const;
    Role             role()   const;
    int              serial() const;

    // ── Static member functions (notes 15.7) ─────────────────────────────────
    // Static functions belong to the CLASS, not to any object — no `this`.
    // Call as IdCard::liveCount(), not card.liveCount() (though both compile).
    static int liveCount();    // how many IdCard objects currently exist
    static int nextSerial();   // value the NEXT constructed card will receive

private:
    // ── Instance (per-object) data ────────────────────────────────────────────
    std::string m_owner {};    // who holds this card
    std::string m_title {};    // their job title
    Role        m_role  { Role::Other };
    int         m_serial {};   // unique ID assigned at construction time

    // ── Static (class-wide) data (notes 15.6) ────────────────────────────────
    // `inline static` lets us define + initialise these right in the header
    // without a separate out-of-class definition line in a .cpp (C++17+).
    // Both live once in the program, shared by every IdCard object.
    inline static int s_liveCount  { 0 };   // count of live IdCard objects
    inline static int s_nextSerial { 1 };   // next serial to hand out (1-based)
};

#endif // IDCARD_H
