// Chapter 17 — Fixed-Size Arrays · Project: Tic-Tac-Toe Referee
// ─────────────────────────────────────────────────────────────────────────────
// This header is the CONTRACT between you and the grader.  It declares all the
// functions the learner must implement.  DO NOT EDIT THIS FILE — tests/tests.cpp
// includes it, and so do BOTH starter/tictactoe.cpp (yours) and
// solution/tictactoe.cpp (the reference).  Change a signature and nothing links.
//
// THE BIG IDEA OF THIS LAB: there are TWO independent exercises here.
//
//   Part A — std::array 2D (tasks 1–5)
//   ─────────────────────────────────────────────────────────────────────────
//   Build a STATELESS TIC-TAC-TOE REFEREE on top of a 3×3 board type alias:
//
//       using Board = std::array<std::array<char, 3>, 3>;
//
//   The Board is always passed by CONST REFERENCE (notes 17.3).  That keeps the
//   calling convention efficient and clean — no copies, no mutation.  Each helper
//   isolates one geometric pattern (row, column, diagonal) so the top-level
//   winner() just calls them in sequence.  The tests feed hand-built boards so
//   the grader never touches stdin.
//
//   Part B — C-style arrays + decay + pointer arithmetic (tasks 6–7)
//   ─────────────────────────────────────────────────────────────────────────
//   Two small utility functions that DEMONSTRATE the two main C-array lessons:
//     • sumScores()  — array DECAY: the parameter looks like an array, but the
//       compiler silently converts it to a pointer. sizeof inside the function
//       gives the POINTER size, not the array size. The README explains why.
//     • firstNegative() — POINTER ARITHMETIC: walk a half-open range [begin,end)
//       with ++p, dereferencing only when needed.  This pattern is the conceptual
//       ancestor of iterators (ch 18) and many standard-library algorithms.
//
// Header guard (ch 2): stops this file being pasted in twice per build.
#ifndef TICTACTOE_H
#define TICTACTOE_H

#include <array>   // std::array (notes 17.1)

// ─── Board type alias (provided — do NOT change) ─────────────────────────────
// std::array<std::array<char,3>,3>:
//   • Outer array: 3 rows   (notes 17.13)
//   • Inner array: 3 columns each
//   • Element type: char  ('X', 'O', or ' ' for empty)
//
// Board[row][col] indexing follows the 2D-array convention from notes 17.12 / 17.13.
// The alias keeps function signatures readable.
using Board = std::array<std::array<char, 3>, 3>;

// ─── PART A: std::array 2D functions ─────────────────────────────────────────

// ─── TASK 1 ──────────────────────────────────────────────────────────────────
// countMark — count how many cells in `board` contain character `ch`.
//
//   countMark(board, 'X')   -> number of X cells (0..9)
//   countMark(board, 'O')   -> number of O cells (0..9)
//   countMark(board, ' ')   -> number of empty cells (0..9)
//
// Constraints: pass `board` by CONST REFERENCE (notes 17.3 — never copy a 2D
// array by value). Use nested range-for loops (notes 17.13).
int countMark(const Board& board, char ch);

// ─── TASK 2 ──────────────────────────────────────────────────────────────────
// isFull — return true if every cell is occupied (no ' ' remains).
//
// Hint: delegate to countMark — one call, one comparison.
bool isFull(const Board& board);

// ─── TASK 3 ──────────────────────────────────────────────────────────────────
// rowWinner / colWinner — detect a winning line.
//
//   rowWinner(board) returns the character that owns an entire row, or ' ' if
//   no row is complete.
//
//   colWinner(board) returns the character that owns an entire column, or ' '.
//
// A row r is won by character ch when board[r][0] == board[r][1] == board[r][2] == ch
// AND ch != ' '.
//
// A column c is won when board[0][c] == board[1][c] == board[2][c] == ch AND ch != ' '.
//
// Constraints: pass `board` by const reference. Use index-based for loops (i, j).
// Return ' ' (the empty-cell sentinel) if no winner is found.
char rowWinner(const Board& board);
char colWinner(const Board& board);

// ─── TASK 4 ──────────────────────────────────────────────────────────────────
// diagWinner — detect a winning diagonal.
//
//   Main diagonal:  board[0][0], board[1][1], board[2][2]
//   Anti-diagonal:  board[0][2], board[1][1], board[2][0]
//
// Return the winning character, or ' ' if neither diagonal is complete.
// Constraints: pass `board` by const reference. No loops needed — just
// compare the three cells directly.
char diagWinner(const Board& board);

// ─── TASK 5 ──────────────────────────────────────────────────────────────────
// winner — combine the helpers above.
//
//   Return 'X' or 'O' if either player has won (any row, column, or diagonal).
//   Return ' ' otherwise (no winner yet — game in progress or draw).
//
// Call rowWinner, colWinner, diagWinner in sequence.  Return the first non-' '
// result you get, or ' ' if none of them find a winner.
char winner(const Board& board);

// isDraw — return true when no one has won AND the board is full.
//
//   Use winner() and isFull() — keep the logic in those helpers.
bool isDraw(const Board& board);

// ─── PART B: C-style arrays + decay + pointer arithmetic ─────────────────────

// ─── TASK 6 ──────────────────────────────────────────────────────────────────
// sumScores — sum a C-style int array.
//
//   sumScores(scores, count) returns the sum of scores[0..count-1].
//
// The parameter `const int scores[]` DECAYS to `const int*` at the call site
// (notes 17.8).  Inside this function, `scores` IS a pointer — sizeof(scores)
// gives the POINTER size (typically 8 bytes on 64-bit), not the array size.
// The README walks through why; the code here just uses the pointer + count
// to sum the elements with a loop (avoid sizeof inside this body).
//
// Use a range-based index loop (for int i = 0; i < count; ++i).
int sumScores(const int scores[], int count);

// ─── TASK 7 ──────────────────────────────────────────────────────────────────
// firstNegative — find the first negative element via POINTER ARITHMETIC.
//
//   firstNegative(begin, end) walks the half-open range [begin, end) using
//   ++p (not an index), dereferencing with *p to inspect each element.
//   Return a pointer to the first element where *p < 0, or `end` if none.
//
// This is the half-open begin/end pattern from notes 17.9, and the conceptual
// ancestor of every standard-library iterator-range algorithm (ch 18).
// Constraint: walk with ++p, NOT p[i] or p + i.
const int* firstNegative(const int* begin, const int* end);

#endif // TICTACTOE_H
