// ============================================================================
//  dynbuf.h  —  the DynBuffer Workbench API  (Chapter 19 — Dynamic Allocation)
// ----------------------------------------------------------------------------
//  This header DECLARES five free functions that manage raw int arrays on the
//  heap using new[] / delete[].  DO NOT EDIT THIS FILE — the grader
//  (tests/tests.cpp) and both starter/dynbuf.cpp and solution/dynbuf.cpp
//  include it.  Changing a signature breaks the build.
//
//  THE BIG IDEA OF THIS LAB
//  ──────────────────────────────────────────────────────────────────────────
//  Every competent C++ programmer needs to *understand* what std::vector does
//  for you under the hood.  This workbench builds each piece by hand:
//
//    makeBuffer   — new[] creates a heap array of any runtime-determined size.
//    destroyBuffer— delete[] releases it; we null out the pointer through a
//                   reference (ch-12 ref-to-pointer paying off) so callers can't
//                   accidentally dereference the now-freed address.
//    cloneBuffer  — a DEEP copy: two independent arrays, not a pointer alias.
//    resizeBuffer — the grow-and-move pattern that std::vector automates
//                   (and that LLVM's SmallVector uses internally).
//    bufferSum    — an observer: const pointer + length, no ownership change.
//
//  CS6340 tie-in: every time you see an LLVM function like
//      void processCounters(unsigned* counters, int n);
//  you are staring at this same contract — a raw pointer carries no length and
//  no ownership information; you must read the docs or the naming convention.
//  The point of this lab is to feel that fragility in your hands.
//
//  Header guard (ch-02 / 2.12):
// ============================================================================
#ifndef DYNBUF_H
#define DYNBUF_H

// ─── TASK 1 ──────────────────────────────────────────────────────────────────
// makeBuffer(n, fill) — allocate a heap array of `n` ints and set every
// element to `fill`.  Returns the owning pointer.
//
// Precondition: n >= 0  (a zero-length dynamic array is technically valid;
//   new int[0] returns a non-null pointer you must still delete[]).
//
// Ownership contract: the CALLER owns the returned pointer and must
// eventually call delete[] (or pass it to destroyBuffer).
int* makeBuffer(int n, int fill);

// ─── TASK 2 ──────────────────────────────────────────────────────────────────
// destroyBuffer(p) — delete[] the array pointed to by `p`, then SET `p` to
// nullptr through the reference.  The ref-to-pointer signature (int*& p) lets
// this function WRITE BACK to the caller's pointer variable — the same
// mechanism as an out-parameter (ch-12 notes: references as in-out params).
//
// Nulling the pointer after delete is the single best defence against
// accidental use-after-free (dangling pointer danger, notes 19.1).
//
// Precondition: p is either a valid owning heap-array pointer OR nullptr.
// (Deleting nullptr is a no-op, and assigning nullptr to nullptr is harmless.)
void destroyBuffer(int*& p);

// ─── TASK 3 ──────────────────────────────────────────────────────────────────
// cloneBuffer(src, n) — deep-copy: allocate a fresh array of `n` ints and
// copy every element from src[0..n-1] into it.  Returns the new owning
// pointer.  Caller owns the returned pointer; `src` is not modified and is
// NOT transferred.
//
// This is a DEEP copy — after cloneBuffer the two arrays are independent.
// Changing one does NOT change the other (unlike copying a pointer, which
// gives you a SECOND owner pointing at the SAME memory — a double-free waiting
// to happen).
//
// Preconditions: src != nullptr if n > 0; n >= 0.
int* cloneBuffer(const int* src, int n);

// ─── TASK 4 ──────────────────────────────────────────────────────────────────
// resizeBuffer(p, oldN, newN) — reallocate to a different length:
//   1. new[] a fresh array of `newN` ints (value-initialized to 0).
//   2. Copy min(oldN, newN) elements from the old array into the new one.
//   3. delete[] the old array.
//   4. Set `p` (through the reference) to point at the new array.
//
// After resizeBuffer returns, the caller's pointer `p` refers to the new
// (possibly larger or smaller) array.  If newN > oldN the extra slots are 0.
// If newN < oldN the prefix of min(oldN,newN) elements is preserved.
//
// This is the exact sequence std::vector performs internally when it grows.
// (notes 19.2: "Resizing means allocating a new array")
//
// Preconditions: p is a valid owning heap-array pointer; oldN >= 0; newN >= 0.
void resizeBuffer(int*& p, int oldN, int newN);

// ─── TASK 5 ──────────────────────────────────────────────────────────────────
// bufferSum(buf, n) — return the sum of all n elements.  This is a PURE
// OBSERVER: it takes the pointer by value (copy of the address), the array is
// marked const, and nothing is allocated or freed.
//
// The const pointer makes it clear this function does not own or modify the
// array.  In LLVM you see this constantly:
//     int64_t sum(const int64_t* values, size_t count);
//
// Preconditions: buf != nullptr if n > 0; n >= 0.
int bufferSum(const int* buf, int n);

#endif // DYNBUF_H
