// Chapter 6 — Operators · Project: Day-One Triage Console
// ─────────────────────────────────────────────────────────────────────────────
// This header is the CONTRACT between you and the grader. It declares the nine
// pure functions you must implement. DO NOT EDIT THIS FILE — the tests in
// tests/tests.cpp include it, and so do BOTH starter/triage.cpp (yours) and
// solution/triage.cpp (the reference). Change a signature here and nothing links.
//
// "Pure" means: each function looks only at its arguments and returns a value.
// No input, no output, no global state, no loops. The grader supplies the
// repetition — it calls each function across MANY inputs — so you never write a
// loop (those are Chapter 8). Your whole job is to get the OPERATORS right.
//
// Header guard (Chapter 2): stops this file being pasted in twice per build.
#ifndef TRIAGE_H
#define TRIAGE_H

#include <string_view>   // std::string_view  — a cheap, non-owning view (Chapter 5)

// ─── TASK 1 ──────────────────────────────────────────────────────────────────
// Is `value` even? Remainder operator `%` + the conditional operator `?:`.
bool isEven(int value);

// Classify parity as a label. Return "even" or "odd" using ONE `?:` expression.
std::string_view classifyParity(int value);

// ─── TASK 2 ──────────────────────────────────────────────────────────────────
// FizzBuzz as a CATEGORY for a single number (no loop, no printing):
//   divisible by both 3 and 5 -> "fizzbuzz"
//   divisible by 3 only       -> "fizz"
//   divisible by 5 only       -> "buzz"
//   otherwise                 -> "number"
std::string_view fizzbuzzCategory(int value);

// ─── TASK 3 ──────────────────────────────────────────────────────────────────
// Gregorian leap year via LOGICAL operators (&&, ||) — no `if`, one expression:
//   divisible by 4 AND (NOT divisible by 100 OR divisible by 400).
bool isLeapYear(int year);

// ─── TASK 4 ──────────────────────────────────────────────────────────────────
// Safe floating-point "equality": true when |a - b| <= epsilon.
// (Never compare calculated doubles with ==.)
bool approxEqual(double a, double b, double epsilon);

// ─── TASK 5 ──────────────────────────────────────────────────────────────────
// Wrap `index` into [0, size) the way a ring buffer needs — ALWAYS non-negative,
// even for negative indices. (Raw `%` can go negative in C++.) Assume size > 0.
int wrapIndex(int index, int size);

// ─── TASK 6 ──────────────────────────────────────────────────────────────────
// Instrumentation gate (the CS6340 tie-in): fire only when we still have budget
// AND this instruction lands on the sampling stride.
//   true  <=>  (sampleEvery > 0) AND (budgetRemaining > 0)
//              AND (instructionIndex % sampleEvery == 0)
// Short-circuit `&&` must guard the `%` so you never divide when sampleEvery is 0.
bool shouldSampleInstruction(int instructionIndex, int sampleEvery, int budgetRemaining);

// ─── TASK 7 ──────────────────────────────────────────────────────────────────
// Ticket routing from a numeric severity score (relational + nested `?:`):
//   score >= 90 -> "P0"
//   score >= 70 -> "P1"
//   score >= 40 -> "P2"
//   otherwise   -> "P3"
std::string_view ticketPriority(int score);

// ─── TASK 8 ──────────────────────────────────────────────────────────────────
// Exactly-one-of (logical XOR). C++ has no logical-XOR operator, but for two
// bool operands, `!=` means "exactly one is true". Return that.
bool exactlyOneSource(bool fromFile, bool fromStdin);

// ─── TASK 9 ──────────────────────────────────────────────────────────────────
// Integer power base^exponent using std::pow (C++ has NO `**` operator; `^` is
// bitwise XOR, not exponent). std::pow returns double — convert back to int.
// Assume exponent >= 0 and the result fits in an int.
int powInt(int base, int exponent);

#endif // TRIAGE_H
