// ============================================================================
//  fraction.h  —  Fraction v2: operator-overloaded rational numbers  (Ch 21)
// ----------------------------------------------------------------------------
//  This header is the CONTRACT between you and the grader. It DECLARES every
//  operator the learner must implement. DO NOT EDIT THIS FILE — tests/tests.cpp
//  and both starter/ and solution/ include it. Change a signature and nothing
//  links.
//
//  YOU BUILT THE FIRST VERSION in Chapter 14. That Fraction had:
//    • Default and two-argument constructors (with reduce())
//    • Const accessors: numerator(), denominator(), isValid()
//    • Member functions: equals(), multipliedBy()
//    • Print helpers: print(), toString()
//
//  THIS VERSION, Fraction v2, keeps all of that and REPLACES the named helpers
//  with OPERATOR OVERLOADS, so Fraction feels like a built-in numeric type:
//
//    Fraction a{1,2}, b{1,3};
//    Fraction c { a * b };           // operator*(Fraction, Fraction)
//    Fraction d { a + b };           // operator+(Fraction, Fraction)
//    bool same  { a == b };          // operator==
//    bool diff  { a != b };          // operator!=
//    bool less  { b < a };           // operator<
//    Fraction neg { -a };            // unary operator-
//    ++a;                            // prefix  operator++
//    a++;                            // postfix operator++
//    std::cout << a;                 // operator<<
//
//  ── MEMBER vs FRIEND design (notes 21.1, 21.2, 21.4, 21.5, 21.6) ─────────
//
//    operator<<   MUST be non-member (left operand is std::ostream, not Fraction).
//    Binary arith (+, *, Fraction*int)  symmetric -> friend non-member.
//    Comparison (==, !=, <)             symmetric -> friend non-member.
//    Unary (-)                          one operand -> member.
//    Prefix/postfix ++                  mutates the current object -> member.
//
//  ── INVARIANT (same as Ch 14) ────────────────────────────────────────────
//    m_denominator is always STRICTLY POSITIVE after construction.
//    reduce() enforces this: negative denominator is absorbed into numerator;
//    both parts are divided by their GCD. So equal fractions have IDENTICAL
//    stored fields — operator== is a simple field comparison (notes 21.7).
//
//  ── OVERFLOW GUARD (engineering note — not from the chapter) ──────────────
//    operator< uses cross-multiplication:  a/b < c/d  iff  a*d < b*c. The
//    ordering idea is notes 21.7; the integer-overflow caution below is our
//    own engineering aside (the note does not discuss it).
//    The tests keep all values small (|num| ≤ 20, |den| ≤ 20) so a*d and b*c
//    never leave the int range. Your code doesn't need a runtime overflow check,
//    but never blindly cross-multiply large fractions without thinking of this.
//
//  CS6340 lens: LLVM source is dense with overloaded operators — iterator
//    comparison (!=, ++), stream diagnostics (<<), container subscript ([]).
//    After this lab you will read that code without a second glance.
// ============================================================================

#ifndef FRACTION_H
#define FRACTION_H

#include <iostream>   // std::ostream (for operator<<)
#include <string>     // std::string, std::to_string (for toString())

class Fraction
{
public:

    // ── Constructors (provided — same as Ch 14) ────────────────────────────

    // Default: represents 0/1.
    Fraction()
        : m_numerator   { 0 }
        , m_denominator { 1 }
    {}

    // Two-argument: Fraction{3, 4} -> 3/4, normalized by reduce().
    // If d == 0, falls back to n/1 (invalid input guard).
    Fraction(int n, int d)
        : m_numerator   { n }
        , m_denominator { d }
    {
        if (m_denominator == 0)
            m_denominator = 1;
        reduce();
    }

    // Single-argument whole number: explicit to block implicit int->Fraction.
    explicit Fraction(int w)
        : m_numerator   { w }
        , m_denominator { 1 }
    {}

    // ── Accessors (provided — same as Ch 14) ──────────────────────────────
    int  numerator()   const { return m_numerator;   }
    int  denominator() const { return m_denominator; }
    bool isValid()     const { return m_denominator != 0; }

    // toString() — provided, used by tests for readable failure messages.
    std::string toString() const
    {
        return std::to_string(m_numerator) + '/' + std::to_string(m_denominator);
    }

    // ─────────────────────────────────────────────────────────────────────────
    //  OPERATOR DECLARATIONS — these are what YOU implement in starter/fraction.cpp
    // ─────────────────────────────────────────────────────────────────────────

    // ── TASK 1: operator* (Fraction * Fraction) ───────────────────────────
    //   (a/b) * (c/d) = (a*c) / (b*d), then reduce.
    //   Symmetric -> friend non-member (notes 21.2).
    friend Fraction operator*(const Fraction& lhs, const Fraction& rhs);

    // ── TASK 2: operator* (Fraction * int)  and  (int * Fraction) ─────────
    //   Treat the int as a whole-number fraction n/1 (notes 21.2 mixed operands).
    friend Fraction operator*(const Fraction& f, int n);
    friend Fraction operator*(int n, const Fraction& f);

    // ── TASK 3: operator+ ─────────────────────────────────────────────────
    //   (a/b) + (c/d) = (a*d + b*c) / (b*d), then reduce.
    //   Symmetric -> friend non-member.
    friend Fraction operator+(const Fraction& lhs, const Fraction& rhs);

    // ── TASK 4: operator== and operator!= ────────────────────────────────
    //   Because both fractions are fully reduced, equality is a field compare.
    //   != is expressed in terms of == (notes 21.7 — minimize redundancy).
    friend bool operator==(const Fraction& lhs, const Fraction& rhs);
    friend bool operator!=(const Fraction& lhs, const Fraction& rhs);

    // ── TASK 5: operator< ─────────────────────────────────────────────────
    //   a/b < c/d  iff  a*d < b*c  (cross-multiplication; denominators > 0
    //   so the inequality direction is preserved).
    //   Keep test values small — see overflow note in the file header.
    friend bool operator<(const Fraction& lhs, const Fraction& rhs);

    // ── TASK 6: unary operator- (negation) ────────────────────────────────
    //   Returns a new Fraction with the numerator sign flipped.
    //   One operand -> member function (notes 21.6).
    Fraction operator-() const;

    // ── TASK 7: prefix operator++ (add 1 = denominator/denominator) ───────
    //   Adds exactly 1 to the fraction: result = (num + den) / den, reduced.
    //   Prefix: mutates *this and returns *this by reference (notes 21.8).
    Fraction& operator++();

    // ── TASK 8: postfix operator++ (the dummy-int overload) ────────────────
    //   Returns the OLD value by value THEN increments.
    //   The dummy `int` parameter is the C++ syntax marker that distinguishes
    //   postfix from prefix — it is unused (the compiler passes 0 for the x++
    //   form); never read it in your body (notes 21.8).
    Fraction operator++(int);

    // ── TASK 9: operator<< (stream insertion) ─────────────────────────────
    //   Must be non-member: left operand is std::ostream, not Fraction (21.4).
    //   Output format: "num/den"  e.g. Fraction{3,4} prints as "3/4".
    //   Return the stream by reference so chaining works: cout << a << b.
    //   Declared friend so it can read private m_numerator / m_denominator.
    friend std::ostream& operator<<(std::ostream& out, const Fraction& f);

private:

    int m_numerator   {};   // carries the sign; may be negative, zero, positive
    int m_denominator {};   // ALWAYS > 0 after construction (class invariant)

    // ── Private helpers (provided — same as Ch 14) ──────────────────────

    // gcd — Euclidean greatest common divisor on magnitudes.
    // Private implementation detail of reduce().
    int gcd(int a, int b) const
    {
        if (a < 0) a = -a;
        if (b < 0) b = -b;
        while (b != 0)
        {
            int tmp { b };
            b = a % b;
            a = tmp;
        }
        return a;
    }

    // reduce — enforce the class invariant in-place.
    //   1. If denominator < 0, negate both parts so denominator > 0.
    //   2. Divide both by gcd to produce lowest terms.
    void reduce()
    {
        if (m_denominator < 0)
        {
            m_numerator   = -m_numerator;
            m_denominator = -m_denominator;
        }
        int g { gcd(m_numerator, m_denominator) };
        if (g > 1)
        {
            m_numerator   /= g;
            m_denominator /= g;
        }
    }
};

#endif // FRACTION_H
