// Chapter 28 — Input and Output · Project: The Report Engine
// ─────────────────────────────────────────────────────────────────────────────
// This header is the CONTRACT between you and the grader. It declares the five
// API functions that build a formatted score-report table and round-trip it
// through a real file. DO NOT EDIT THIS FILE — tests/tests.cpp includes it, and
// so do BOTH starter/report.cpp (yours) and solution/report.cpp (the reference).
//
// THE BIG IDEA OF THIS LAB: streams are a UNIFORM ABSTRACTION over strings,
// files, and the terminal. Every function in this API either:
//   (a) accepts / returns an std::string (built internally with ostringstream), or
//   (b) accepts a std::ostream& / std::istream& so it works with ANY stream kind.
//
// Why does this matter for CS6340?
//   In Lab 1 you will: read seed-corpus lines from a file (ifstream), log
//   coverage results to another (ofstream), and pass diagnostic streams around.
//   The same output function can write to std::cout for dev runs and to an
//   ofstream in the autograder harness — zero code change, because both ARE
//   std::ostream. This lab builds that muscle.
//
// Notes cross-reference: the section numbers below refer to
//   ../../notes/chapter-28.md (always check before citing).
//
// Header guard (Chapter 2): prevents multiple-inclusion ODR errors.
#ifndef REPORT_H
#define REPORT_H

#include <istream>    // std::istream     — base input  (notes 28.1)
#include <ostream>    // std::ostream     — base output (notes 28.1)
#include <string>     // std::string
#include <vector>     // std::vector (Chapter 16 — reused here)

// ─────────────────────────────────────────────────────────────────────────────
// ScoreRecord — one parsed entry from a raw "name score" line.
//   ok    = true  -> the parse succeeded; name and score are valid
//   ok    = false -> the line was malformed; name and score are undefined
//   name  = the alphanumeric name token (no spaces)
//   score = the numeric score  (must be in [0.0, 100.0])
// ─────────────────────────────────────────────────────────────────────────────
struct ScoreRecord
{
    bool        ok    { false };
    std::string name  {};
    double      score { 0.0  };
};

// ─── TASK 1 ──────────────────────────────────────────────────────────────────
// parseScoreLine(line) — parse a "name score" line with std::istringstream.
//
// Input: a std::string containing exactly one name token followed by one
//        floating-point score, e.g. "Ada 92.5" or "  Bob   88.0  ".
//        Whitespace before/between/after the two tokens is fine (>> skips it).
//
// Return a ScoreRecord with:
//   ok = true  if extraction of BOTH name AND score succeeded
//              AND score is in the range [0.0, 100.0]
//   ok = false for anything else (malformed, out-of-range, extra junk is ok
//              to ignore — the first two fields are all we need)
//
// Constraint: use std::istringstream (notes 28.4) for extraction; do NOT use
// hand-rolled string parsing (substr, find, etc.). Check stream state with
// if(in >> name >> score) (notes 28.5).
//
// Hint: the extraction operator >> already skips leading whitespace.
ScoreRecord parseScoreLine(const std::string& line);

// ─── TASK 2 ──────────────────────────────────────────────────────────────────
// formatRow(name, score) — format one aligned table row as a std::string.
//
// Return a string of EXACTLY this form (the grader does exact-string asserts):
//
//   "Ada         92.5"   — name LEFT-justified in a 10-char wide field (16 total),
//                          score RIGHT-justified in a 6-char field, 1 decimal.
//   "Ada       " = 10 chars (3-char name + 7 spaces)
//   "  92.5"    =  6 chars (2 spaces + 92.5) — right-aligned in 6-char field
//   Total row width = 16 chars.
//
// Layout constants (hardcoded is fine — they're part of the format spec):
//   NAME_WIDTH  = 10   (std::left + std::setw(10))
//   SCORE_WIDTH =  6   (std::right + std::setw(6))
//   SCORE_PREC  =  1   (std::fixed + std::setprecision(1))
//
// Constraint: use std::ostringstream (notes 28.4) + <iomanip> manipulators
// (std::left, std::right, std::setw, std::fixed, std::setprecision — notes 28.3).
// Do NOT build the string with manual padding (spaces + std::to_string, etc.).
//
// Tricky bit: std::setw resets after every item; std::fixed + std::setprecision
// persist. Make sure the ORDER of manipulators matches the expected layout.
std::string formatRow(const std::string& name, double score);

// ─── TASK 3 ──────────────────────────────────────────────────────────────────
// buildReport(records) — assemble a complete multi-line table.
//
// Given a vector of valid ScoreRecords (all ok == true), produce a string of
// this exact shape (header + separator are 16 chars wide; each data row is
// formatRow(...) — also 16 chars — plus a trailing '\n'):
//
//   "Name       Score\n"      <- header
//   "--------- ------\n"       <- separator
//   "Ada         92.5\n"       <- each data row is formatRow(r.name, r.score)+'\n'
//   "Bob         88.0\n"
//   ...
//
// EXACT column layout (no trailing spaces on the header/separator lines):
//   Header:    "Name" left in setw(10) = "Name"+6 spaces, then "Score" right in
//              setw(6) = 1 leading space+"Score" -> "Name       Score" (7-space gap)
//   Separator: "---------" (9 dashes, left setw(9)) + " " + "------" (6 right)
//
// The expected header row string is:
//   "Name       Score\n"    (Name + 7 spaces + Score)
// The expected separator row string is:
//   "--------- ------\n"   (9 dashes + 1 space + 6 dashes)
//
// Each data row: formatRow(r.name, r.score) + '\n'
//
// Constraint: build the whole report with a SINGLE std::ostringstream (do not
// concatenate multiple buildReport calls). Use formatRow for data rows.
// An empty records vector produces only the header + separator (2 lines).
std::string buildReport(const std::vector<ScoreRecord>& records);

// ─── TASK 4 ──────────────────────────────────────────────────────────────────
// writeReport(path, report) — write the report string to a file.
// readReportFirstLine(path) — read the FIRST line back from that file.
//
// writeReport:
//   Open path with std::ofstream (notes 28.6). If the open fails, do nothing
//   (just return). Otherwise write the `report` string into the file.
//   The file is created (or truncated) by default — that is fine for this task.
//
// readReportFirstLine:
//   Open path with std::ifstream (notes 28.6). If the open fails, return "".
//   Otherwise read the FIRST LINE with std::getline and return it.
//   (A first-line round-trip check is a lightweight way to verify the file
//   write: if the header came back, the write worked.)
//
// Constraint: use std::ofstream / std::ifstream (not fstream). Always check
// whether opening succeeded with `if (!file)` (notes 28.6). Do NOT use C stdio.
void        writeReport(const std::string& path, const std::string& report);
std::string readReportFirstLine(const std::string& path);

// ─── TASK 5 ──────────────────────────────────────────────────────────────────
// countValidInts(in) — count integers extracted from a stream until EOF/failure.
//
// Extract integers from `in` one at a time with `>>`. For each successful
// extraction, increment the count. Stop as soon as extraction fails (either EOF
// or a non-integer token). Return the count.
//
// Key insight (notes 28.5): once failbit is set, every subsequent extraction
// on the SAME stream also fails — so once you hit junk, stop immediately.
// The caller feeds you an istringstream so you can test it with a known string.
//
// Example: "10 20 30"   -> 3  (all valid)
//          "10 abc 30"  -> 1  (stops at "abc"; 30 is never seen)
//          "abc"        -> 0  (fails on the first token)
//          ""           -> 0  (empty stream, EOF immediately)
//
// Constraint: use a while loop whose condition IS the extraction attempt
// (i.e. `while (in >> val)`). Do NOT call in.clear() — the function should
// stop at the first failure, not try to recover. (notes 28.5)
int countValidInts(std::istream& in);

#endif // REPORT_H
